### ISSUE TITLE
Fails at 86%

### ISSUE THREAD

**Issue by ninep9up** [destroyhimmyrobots/epwing-exporter#1]
Says me who spent two days on it and feels like an idiot. Please share binaries.

**Comment by destroyhimmyrobots** [comment]
Hi there - I have not worked on this project for quite a while. 

While I do not know what issue you are having, I do not expect uploading a binary build will resolve it.

I would recommend creating a debug build (via `cmake -DCMAKE_BUILD_TYPE=Debug` or just temporarily changing the default [here](https://github.com/destroyhimmyrobots/epwing-exporter/blob/master/CMakeLists.txt#L8)) to help diagnose your issue.

Sometimes, even the dictionary itself can be a problem. If you have any more details, let me know - I am happy to fix any real bugs you find, or help point you to upstream places where you can open issues if needed.

**Comment by destroyhimmyrobots** [comment]
I will close this issue since there is no description of what exactly is failing, or why. Feel free to open a separate issue if you collect some logs or debugging information.

**Comment by ninep9up** [comment]
> 
> 
> I will close this issue since there is no description of what exactly is failing, or why. Feel free to open a separate issue if you collect some logs or debugging information.

I fail at building it, I've got Ubuntu 16 running as VM, installed some of dependencies needed, but around 70+ or 80+ it fails saying there's } expected somewhere in gaiji sources

**Comment by ninep9up** [comment]
I've tried last OpenSuse first, but it was failing at experimental/filesystem, so I reckoned the problem was with gcc, so I went to Ubuntu 18 which had some hardcoded dependencies within cmake which was failing now, similar issues stating it's because 3.16+, so I went to 16, but now it failed of syntax, lol.

**Comment by ninep9up** [comment]
You can provide the desired setup if you want, so I try to go with it, otherwise it's just two wasted days for me.

**Comment by destroyhimmyrobots** [comment]
Sounds like an issue with the build environment. Since you are on Linux, I added a Dockerfile in https://github.com/destroyhimmyrobots/epwing-exporter/commit/5e39bcbdaeb1c4ad2447518f06ef4560f2fc8937 and also updated the build instructions.

The TL;DR is that you will need to run `cmake .. ; make` more than once. Hope this helps.
